[kafka]
urls = "localhost:9092"
decoders = "avro_confluent_schema_registry"

[confluent-schema-registry]
url = "http://localhost:8081"

[kafka-connect]
url = "http://localhost:8083"

[server]
port = 9999