[kafka]
urls = "localhost:9092"
key-decoders = "avro_confluent_schema_registry,utf8"
value-decoders = "avro_confluent_schema_registry,utf8"

[confluent-schema-registry]
url = "http://localhost:8081"

[kafka-connect]
url = "http://localhost:8083"

[server]
port = 9999