version: '2.1'

services:
    krowser:
      image: tzachs/krowser:latest
      restart: unless-stopped
      hostname: krowser
      ports:
        - "9999:9999"
      environment:
        KROWSER__KAFKA__URLS: localhost:9092
        KROWSER__CONFLUENT_SCHEMA_REGISTRY__URL: http://localhost:8081
